name: Build and Deploy Bookdown

on:
  push:
    branches: main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1'

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("bookdown", "rmarkdown"))'

      - name: Copy shared resources
        run: |
          for dir in Y1 Y2; do
            cp style.css "$dir/"
          done

      - name: Build Y1 book
        working-directory: Y1
        run: Rscript -e 'bookdown::render_book("index.Rmd")'

      - name: Build Y2 book
        working-directory: Y2
        run: Rscript -e 'bookdown::render_book("index.Rmd")'

      - name: Assemble deploy folder
        run: |
          mkdir -p _deploy/Y1 _deploy/Y2
          cp -r Y1/_site/* _deploy/Y1/
          cp -r Y2/_site/* _deploy/Y2/
          echo '<html><head><meta http-equiv="refresh" content="0;url=Y1/"></head></html>' > _deploy/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: _deploy
